[2025-07-15T20:06:40.137+0000] {processor.py:153} INFO - Started process (PID=53) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:06:40.140+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:06:40.144+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:06:40.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:06:40.615+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:06:40.605+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:06:40.619+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:06:40.649+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.520 seconds
[2025-07-15T20:07:11.110+0000] {processor.py:153} INFO - Started process (PID=63) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:07:11.112+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:07:11.114+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:07:11.113+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:07:11.491+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:07:11.482+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:07:11.493+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:07:11.524+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.429 seconds
[2025-07-15T20:07:41.959+0000] {processor.py:153} INFO - Started process (PID=65) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:07:41.960+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:07:41.961+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:07:41.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:07:42.326+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:07:42.316+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:07:42.328+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:07:42.358+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.403 seconds
[2025-07-15T20:08:12.855+0000] {processor.py:153} INFO - Started process (PID=67) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:08:12.857+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:08:12.858+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:08:12.858+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:08:13.224+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:08:13.213+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:08:13.226+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:08:13.265+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.414 seconds
[2025-07-15T20:08:43.355+0000] {processor.py:153} INFO - Started process (PID=69) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:08:43.356+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:08:43.358+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:08:43.358+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:08:43.692+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:08:43.682+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:08:43.694+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:08:43.725+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.375 seconds
[2025-07-15T20:09:13.807+0000] {processor.py:153} INFO - Started process (PID=71) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:09:13.809+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:09:13.810+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:09:13.810+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:09:14.138+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:09:14.128+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:09:14.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:09:14.176+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.375 seconds
[2025-07-15T20:09:44.741+0000] {processor.py:153} INFO - Started process (PID=73) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:09:44.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:09:44.744+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:09:44.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:09:45.096+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:09:45.086+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:09:45.099+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:09:45.129+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.393 seconds
[2025-07-15T20:10:15.178+0000] {processor.py:153} INFO - Started process (PID=75) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:10:15.180+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:10:15.182+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:10:15.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:10:15.517+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:10:15.507+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:10:15.519+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:10:15.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.380 seconds
[2025-07-15T20:10:45.635+0000] {processor.py:153} INFO - Started process (PID=77) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:10:45.636+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:10:45.638+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:10:45.637+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:10:45.998+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:10:45.986+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:10:46.000+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:10:46.039+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.410 seconds
[2025-07-15T20:11:16.527+0000] {processor.py:153} INFO - Started process (PID=79) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:11:16.529+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:11:16.530+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:11:16.530+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:11:16.862+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:11:16.853+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:11:16.864+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:11:16.895+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.371 seconds
[2025-07-15T20:11:47.059+0000] {processor.py:153} INFO - Started process (PID=81) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:11:47.060+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:11:47.062+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:11:47.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:11:47.392+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:11:47.378+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:11:47.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:11:47.426+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.373 seconds
[2025-07-15T20:12:17.933+0000] {processor.py:153} INFO - Started process (PID=83) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:12:17.936+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:12:17.939+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:12:17.938+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:12:18.436+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:12:18.425+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:12:18.438+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:12:18.481+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.558 seconds
[2025-07-15T20:12:48.864+0000] {processor.py:153} INFO - Started process (PID=85) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:12:48.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:12:48.867+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:12:48.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:12:49.432+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:12:49.424+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:12:49.434+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:12:49.473+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.616 seconds
[2025-07-15T20:13:19.809+0000] {processor.py:153} INFO - Started process (PID=87) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:13:19.812+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:13:19.813+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:13:19.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:13:20.266+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:13:20.257+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:13:20.268+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:13:20.309+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.507 seconds
[2025-07-15T20:13:50.578+0000] {processor.py:153} INFO - Started process (PID=89) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:13:50.580+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:13:50.581+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:13:50.581+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:13:51.300+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:13:51.193+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:13:51.302+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:13:51.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.765 seconds
[2025-07-15T20:14:21.723+0000] {processor.py:153} INFO - Started process (PID=91) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:14:21.725+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:14:21.726+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:14:21.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:14:22.225+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:14:22.218+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:14:22.227+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:14:22.253+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.533 seconds
[2025-07-15T20:14:52.680+0000] {processor.py:153} INFO - Started process (PID=93) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:14:52.682+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:14:52.685+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:14:52.683+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:14:53.262+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:14:53.241+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:14:53.265+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:14:53.318+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.645 seconds
[2025-07-15T20:15:23.713+0000] {processor.py:153} INFO - Started process (PID=95) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:15:23.714+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:15:23.716+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:15:23.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:15:24.097+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:15:24.088+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:15:24.099+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:15:24.130+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.423 seconds
[2025-07-15T20:15:54.211+0000] {processor.py:153} INFO - Started process (PID=97) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:15:54.213+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:15:54.215+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:15:54.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:15:54.620+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:15:54.610+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:15:54.623+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:15:54.652+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.447 seconds
[2025-07-15T20:16:25.146+0000] {processor.py:153} INFO - Started process (PID=99) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:16:25.148+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:16:25.150+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:16:25.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:16:25.496+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:16:25.487+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:16:25.498+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:16:25.528+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.391 seconds
[2025-07-15T20:16:55.613+0000] {processor.py:153} INFO - Started process (PID=102) to work on /opt/airflow/dags/DAG 1.py
[2025-07-15T20:16:55.615+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/DAG 1.py for tasks to queue
[2025-07-15T20:16:55.616+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:16:55.616+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:16:56.126+0000] {logging_mixin.py:137} INFO - [2025-07-15T20:16:56.117+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/DAG 1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/DAG 1.py", line 2, in <module>
    from sklearn.cluster import KMeans
ModuleNotFoundError: No module named 'sklearn'
[2025-07-15T20:16:56.127+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/DAG 1.py
[2025-07-15T20:16:56.163+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/DAG 1.py took 0.555 seconds
